matrix/lu_decompose.jl
searches/linear_search.jl

This is to start off the matrix folder for algorithms related to matrix.
LU decomposition is as a starter!

added LU decomposition.

---

src/TheAlgorithms.jl
src/sorts/bubble_sort.jl
src/sorts/bucket_sort.jl
src/sorts/counting_sort.jl
src/sorts/exchange_sort.jl
src/sorts/insertion_sort.jl
src/sorts/merge_sort.jl
src/sorts/quick_sort.jl
src/sorts/selection_sort.jl
src/strings/kmp_substring_search.jl
test/sorts.jl
test/strings.jl

Hey sir, I had renamed the below came cased function to underscore
Note: *may be unnecessary but I think it would introduce a more consistent syntax style*
```
1. bubble_sort!
2. bucket_sort!
3. counting_sort!
4. exchange_sort!
5. insertion_sort!
6. merge_sort!
7. quick_sort!
8. selection_sort!
9. contain_substring_with_kmp
```

renamed some camel cased functions to underscore

---

src/project-rosalind/count_nucleotide.jl
test/project-rosalind.jl

Wrong output order in [count_nucleotide.jl](https://github.com/Nikola-Mircic/Julia/blob/main/src/project-rosalind/count_nucleotide.jl) on line 10.

fix: wrong output order

---

src/TheAlgorithms.jl
src/cipher/affine.jl
test/cipher.jl

First time contributing, sorry in advance!
I added an algorithm to encode using an affine cipher, which I essentially just pulled from an [ongoing project of mine](https://github.com/Squalm/Cipher-Tools). I mostly thought this would be relevant because atbash is (if I remember correctly) just a specific affine cipher, so hopefully it is! (and perhaps it would be worth making that clear in the code?)
I've run the tests manually but haven't actually run the tests file because I wasn't sure how to so I may have made a mistake there.

Add Affine Cipher

---

src/TheAlgorithms.jl
src/math/average_absolute_deviation.jl
test/math.jl

The average absolute deviation of a data set is the average of the absolute deviations from the mean.
It is  a measure of statistical dispersion or variability.

Added average absolute deviation

---

test/math.jl

This line
https://github.com/TheAlgorithms/Julia/blob/40586f4c0fc11b9814b7aabef1b01e2975b332c0/src/math/area.jl#L160
is not covered by any on the existing tests. This PR adds missing tests.

tests: check if `area_heron_triangle` throws when input sides do not form a triangle

---

.gitpod.dockerfile

The current [.gitpod.dockerfile](https://github.com/TheAlgorithms/Julia/blob/1ba04f5c3984da98eb0d0a151f729e6445c6488b/.gitpod.dockerfile) does not work.
I decided to use the `workspace-base` instead of `workspace-full-vnc`.

chore: properly install `julia` in `.gitpod.dockerfile`

---

src/searches/interpolation_search.jl
test/searches.jl

The `interpolation_search` is not really tested. This PR adds meaningful test for it and changes `interpolation_search` to return integers.

tests: add tests for `interpolation_search`

---

src/searches/binary_search.jl
src/searches/exponential_search.jl
test/searches.jl

I think it makes more sense to use `int` as a return type of [`binary_search`](https://github.com/TheAlgorithms/Julia/blob/c865d384273f4f09a8581948553d16389593a935/src/searches/binary_search.jl#L62) and [`exponential_search`](https://github.com/TheAlgorithms/Julia/blob/c865d384273f4f09a8581948553d16389593a935/src/searches/exponential_search.jl#L19).

style: use int as the return type

---

test/cipher.jl

This PR adds missing test cases for the function [`caesar`](https://github.com/TheAlgorithms/Julia/blob/8e3c9615dde24a960112d82b95cc96beaf15be9c/src/cipher/caesar.jl#L46).

tests: add missing test cases for `caesar`

---

test/math.jl

I am not sure why `abs` was tested like that.

tests: simplify logic of the tests of `abs`

---

src/matrix/determinant.jl
test/matrix.jl

The [`determinant`](https://github.com/TheAlgorithms/Julia/blob/ede895a5e5e194cf09b184de08313c599463ad84/src/matrix/determinant.jl#L16) function actually [does not throw](https://github.com/TheAlgorithms/Julia/blob/ede895a5e5e194cf09b184de08313c599463ad84/src/matrix/determinant.jl#L19) for _non-square_ inputs. This PR fixes that and adds missing test cases.

fix: make `determinant` throw

---

src/graph/bfs.jl
test/graph.jl

Same as #201 but for [`bfs`](https://github.com/TheAlgorithms/Julia/blob/ede895a5e5e194cf09b184de08313c599463ad84/src/graph/bfs.jl#L31).

refactor: make `bfs` return vector

---

src/graph/dfs.jl
test/graph.jl

Current implementation of [`dfs`](https://github.com/TheAlgorithms/Julia/blob/ede895a5e5e194cf09b184de08313c599463ad84/src/graph/dfs.jl#L31) is not really testable: it displays the nodes. This PR changes that and adds missing tests.

refactor: make `dfs` return vector

---

test/searches.jl

Noticed that there were no test cases for binary searching for an element not present. Added those cases.

test: binary search not found cases added

---

src/longest_increasing_subsequence/binary_search.jl
src/longest_increasing_subsequence/dynamic_programming.jl
test/longest_increasing_subsequence.jl

**Performance improvement**: Use `pushfirst!` directly when creating the result `lis_arr` instead of unnecessarily doing `push!` in a loop and then `reverse!` later
**More Julian code**: Writing generic code is strongly encouraged in Julia, and it's more in line with Julian convention to accept an array of any `Integer` subtype, instead of artificially limiting it to `Int` only.  Since `where T <: Integer` is pretty intuitive and easy to make sense of, it doesn't particularly affect readability. And this makes it clearer which of the arrays used in the function are meant to hold values from the original array (those typed `T`) and which are meant to hold indices (those typed `Int`), which can make it easier to understand the algorithms.

Enhancements to "Longest Increasing Subsequence"

---

test/data_structures.jl

This PR adds test covering this line:
https://github.com/TheAlgorithms/Julia/blob/b5269b4ac579d91d67b5588f91a2ba780f0bacde/src/data_structures/linked_list.jl#L152

tests: add test of `LinkedList.get` for existing value

---

src/project_euler/ProjectEuler.jl
src/project_euler/problem_016.jl
test/project_euler.jl

Added solution to Project Euler's problem 16: Power Digit Sum
[projecteuler.net/problem=16](https://projecteuler.net/problem=16)

Add solution to Project Euler Problem 016

---

src/math/Math.jl
src/math/binary_length.jl
test/math.jl

#207 
- Moved binary_length.jl from the string folder to the math folder.
- Fix incorrect time complexity in the function documentation.
- Added a faster implementation of bin_length.
- Added tests for all the bin_length functions.

Binary Length Improvements

---

src/project_euler/ProjectEuler.jl
src/project_euler/problem_016.jl
src/project_euler/problem_017.jl
src/project_euler/problem_018.jl
src/project_euler/problem_019.jl
src/project_euler/problem_020.jl
test/project_euler.jl

Added solutions to Project Euler 17,18,19 and 20.

Project Euler 17-20

---

test/conversions.jl

This PR adds a test _covering_ this line:
https://github.com/TheAlgorithms/Julia/blob/fa5dd9c754d057e5ba7ce307e7962d8f8ead0fef/src/conversions/weight_conversion.jl#L29

tests: test `weight_conversion` with non existing units

---

test/conversions.jl

This PR adds a test covering this line:
https://github.com/TheAlgorithms/Julia/blob/2dc61a838612c19783730abdc25c104cac3ccf2c/src/conversions/length_conversion.jl#L69
It is similar to #220.

tests: test `length_conversion` with non existing units

---

src/conversions/weight_conversion.jl
test/conversions.jl

[`length_conversion`](https://github.com/TheAlgorithms/Julia/blob/087dac1ce248b4d12dc7a5f5acd828e34e15808c/src/conversions/length_conversion.jl#L82) and [`weight_conversion`](https://github.com/TheAlgorithms/Julia/blob/087dac1ce248b4d12dc7a5f5acd828e34e15808c/src/conversions/weight_conversion.jl#L27) have different signatures - the `value` is in different places. This PR fixes that.

style: unify conversions interface

---

README.md

This project is setup to be used in gitpod. However the gitpod badge is missing in `README.md` (other [The Algorithms](https://github.com/TheAlgorithms/) repos have such badge). This PR adds the missing badge.

docs: add gitpod badge to `README.md`
