TheAlgorithms/Julia

- searches/linear_search.jl
Let's start with a simple one. I am not really familiar with Julia, but I hope this will do.
> Add Linear Search

- math/area_under_curve.jl
- math/collatz_sequence.jl
- math/euler_method.jl
- math/line_length.jl
This is to start the math folder and have collatz sequence as the starter!
> Math folder

- project-rosalind/count_nucleotide.jl
- project-rosalind/dna2rna.jl
This is to start the folder for the solutions to project rosalind in julia
I have added two codes as a starter!
> added project-rosalind folder and some starter

- project-rosalind/reverse_complement.jl
- searches/linear_search.jl
solution to third problem of Project rosalind , reverse complement.
> added reverse complement

- searches/binary_search.jl
my solution to exercism.io julia track
> Add binary search

- matrix/determinant.jl
- searches/linear_search.jl
This code is to find the determinant of a  square matrix using `LU decomposition`.
> added determinant.jl to matrix

- src/searches/exponential_search.jl
> ExponentialSearch

- src/searches/jump_search.jl
> JumpSearch

- src/searches/interpolation_search.jl
> InterpolationSearch

- src/TheAlgorithms.jl
- src/math/armstrong_number.jl
- test/math.jl
> Armstrong Number

- src/TheAlgorithms.jl
- src/strings/is_palindrome.jl
- test/strings.jl
Added  is_palindrome.jl under the src > string folder.
> Add is_palindrome

- src/statistics/variance.jl
> Variance by Pearson method

- src/TheAlgorithms.jl
- src/math/abs.jl
- src/math/area.jl
- src/math/ceil_floor.jl
- test/math.jl
> Some more math functions

- src/TheAlgorithms.jl
- src/math/average_mean.jl
- src/math/average_median.jl
- src/math/average_mode.jl
- test/math.jl
> Mean,Mode,Median

- src/TheAlgorithms.jl
- src/scheduling/fcfs.jl
- test/runtests.jl
- test/scheduling.jl
> First come first serve

- src/TheAlgorithms.jl
- src/math/sum_of_arithmetic_series.jl
- src/math/sum_of_geometric_progression.jl
- test/math.jl
> Sum of Arithmetic & Geomtric progressions

- src/TheAlgorithms.jl
- src/math/perfect_cube.jl
- src/math/perfect_number.jl
- src/math/perfect_square.jl
- test/math.jl
> Perfect cube,number,square

- src/TheAlgorithms.jl
- src/math/factorial.jl
- test/math.jl
> Factorial: iterative & recursive

- src/TheAlgorithms.jl
- src/data_structures/binary_tree/basic_binary_tree.jl
- src/data_structures/disjoint_set/disjoint_set.jl
- test/data_structures.jl
- test/runtests.jl
> add data structures

- src/TheAlgorithms.jl
- src/math/prime_check.jl
- src/math/prime_factors.jl
- test/math.jl
> Prime Check and Prime Factors

- .github/workflows/CI.yml
- src/TheAlgorithms.jl
- test/Project.toml
Small changes to reduce dependencies and a slight improvement in CI tests speed
> CI improvements

- src/TheAlgorithms.jl
- src/math/verlet.jl
- test/math.jl
This is to add verlet integration
I will close the other PR because of the mess and add each file properly in seperate PRs
> added Verlet integration

- src/statistics/variance.jl
- test/statistics.jl
> Document variance

- src/conversions/temparature_conversion.jl
- src/conversions/weight_conversion.jl
- src/math/abs.jl
- src/math/average_mean.jl
- src/math/average_median.jl
- src/math/collatz_sequence.jl
- src/math/factorial.jl
- src/math/perfect_cube.jl
- src/math/perfect_number.jl
- src/math/perfect_square.jl
- src/math/prime_check.jl
- src/math/prime_factors.jl
- test/math.jl
> fix slow things

- Project.toml
- src/TheAlgorithms.jl
- test/Project.toml
- test/math.jl
- test/runtests.jl
- test/statistics.jl
Closes #60 
CI coverage will decrease a little, but it is unavoidable (as some heavy packages were loaded for just one or two tests)
> Clean dependencies

- src/TheAlgorithms.jl
- src/math/combination.jl
- src/math/permutation.jl
- test/math.jl
Added ```combinations``` and ```permutations``` algorithms to the ```math``` folder. Added test according ```CONTRIBUTING.md```.
> add combinations and permutations

- src/TheAlgorithms.jl
- src/sorts/exchange_sort.jl
- test/sorts.jl
Good evening sir, I am Gervin, I took some time and implemented a very beginner-friendly and intuitive algorithm
- Exchange Sort
I am looking forward to your answer and maybe the merge of my commits to your original code.
Thank you in advance.
Gervin Fung
> Implemented Exchange Sort Algorithm

- src/TheAlgorithms.jl
- src/knapsack/dynamic_programming.jl
- src/knapsack/greedy_algorithm.jl
- test/knapsack.jl
Hi sir, I have added a another knapsack algorithm which is the greedy algorithm.
I am looking forward to hearing from you.
Thank you.
Khee Long.
> Added new knapsack algorithm-greedy algorithm

- src/TheAlgorithms.jl
- src/sorts/counting_sort.jl
- test/sorts.jl
Hi sir/madam, 
I am Pei Jin. I have implemented a beginner-friendly sorting algorithm called Counting sort.
I hope you can take a moment to read the algorithm, thank you for your time and consideration.
Regards,
Pei Jin
> implement new sorting algorithm- counting sort

- src/TheAlgorithms.jl
- src/knapsack/dynamic_programming.jl
- src/knapsack/greedy_algorithm.jl
- src/sorts/counting_sort.jl
- test/knapsack.jl
Hi, as mentioned in #75, I have made some amendments to the knapsack algorithms to apply the multiple dispatch approach, feel free to tell me if there are any problems from the changed code. I have also made some changes on the documentation of the counting sort.
> amendment to knapsack algorithm functions

- src/TheAlgorithms.jl
- src/strings/kmp_substring_search.jl
- test/strings.jl
Good day sir, I took some time and have implemented KMP sub-string search as I think it's beneficial to learn why advanced searching algorithm is preferred and how it works and why it has lower time complexity than naive/brute-force algorithm
I look forward to your reply and maybe the merge of my code to the main branch!
Thank you
Regards，
Gervin Fung
> Added KMP substring search

- src/sorts/bubble_sort.jl
(I'm not so good at English, Sorry)
There is such a paragraph in Julia's official document
https://docs.julialang.org/en/v1/manual/style-guide/#Use-naming-conventions-consistent-with-Julia-base/
There is a more concise syntax for exchanging the values of array [j], and array [j + 1]
> Re implementation bubble sort

- src/TheAlgorithms.jl
- src/strings/word_count.jl
- test/strings.jl
This is a program to print the count of words in the given sentence
> Adding word count program

- src/TheAlgorithms.jl
- src/strings/pangram.jl
- test/strings.jl
A pangram is a sentence using every letter of the alphabet at least once.
> Adding program to find pangram

- src/machine_learning/linear_regression.jl
Hi,
I added machine_learning directory, as it was not present. 
Notes that you care about
Thank you
> Adding Machine Learning Algorithms

- src/TheAlgorithms.jl
- src/strings/hamming_distance.jl
- test/strings.jl
I implemented the algorithm to find the hamming distance between two strings. I added tests to the `test/strings.jl`.
> Hamming distance 

- src/TheAlgorithms.jl
- src/math/area.jl
- test/math.jl
- Function to calculate the area of a regular polygon given the number of sides and side length.
- Function to calculate the area of any polygon given the x and y coordinates of the vertices.
> Adding polygon area functions

- src/TheAlgorithms.jl
- src/longest_increasing_subsequence/dynamic_programming.jl
- test/longest_increasing_subsequence.jl
- test/runtests.jl
Longest Increasing Subsequence problem solved by Dynamic Programming approach.
> lis using dp approach

- src/longest_increasing_subsequence/dynamic_programming.jl
- test/longest_increasing_subsequence.jl
Tests improved to cover corner cases in LIS.
> improving tests and corner cases

- src/TheAlgorithms.jl
- src/longest_increasing_subsequence/binary_search.jl
- test/longest_increasing_subsequence.jl
Algorithm for LIS problem using Binary Search + Dynamic Programming.
> LIS solution by Binary Search approach

- src/strings/binary_length.jl
The file is short and sweet providing necessary context. I placed it in strings because of how it works, but if there's a more appropriate file please move it or inform me appropriately. Any improvements can be shuttled my way as well.
I've left it out of the file for continuity sake, but I originally developed this as a part of my Youtube Series which you can find on my github.
> Binary_Length.jl

- src/math/factorial.jl
The factorial_iterative function was performing recursion and vice versa.
> Fix factorial_iterative and factorial_recursive functions

- src/TheAlgorithms.jl
- src/math/partition.jl
- src/math/partitions.jl
- test/math.jl
An implementation to compute the partitions of an Integer using the recursive formula.
Partitions of n is equal to the sum of partitions of n with k parts.
$$P \\left ( n \\right ) = \\sum_{k=1}^{n} P_{k} \\left ( n \\right )$$
Partitions of n with k parts is the sum of partitions of n-1 with k-1 parts and, partitions of n-k with k parts.
$$P_{k}\\left ( n \\right ) = 
P_{k-1}\\left ( n - 1 \\right ) + P_{k}\\left ( n - k \\right )$$
> Integer Partitions (Partition Function)

- src/TheAlgorithms.jl
- src/dynamic_programming/coin_change.jl
- test/dynamic_programming.jl
- test/runtests.jl
Hi,
I added a dynamic programming algorithm for the coin change problem.
> Add coin change dynamic programming

- src/TheAlgorithms.jl
- src/data_structures/fenwick_tree.jl
- test/data_structures.jl
Implementation of the Fenwick tree data structure, also known as Binary Index tree.
> Fenwick tree ( Binary Index Tree )

- src/TheAlgorithms.jl
- src/math/area.jl
- test/math.jl
Hi sir, I am Jun Han, I took some time and implemented a new algorithm
- Surface area of cuboid
I am looking forward to your answer and maybe the merge of my commits to your original code.
Thank you in advance.
JunHan Ooi
> New surfarea_cuboid algorithm

- src/TheAlgorithms.jl
- src/math/eulers_totient.jl
- test/math.jl
Add Euler's Totient Function
It is defined as the number of positive integers less than or equal to n which are relatively prime to n.
> Add Euler's Totient Function

- src/graph/bfs.jl
- src/graph/dfs.jl
Added iterative implementations of DFS and BFS on unweighted graphs and included documentation in accordance with [CONTRIBUTING.md](https://github.com/TheAlgorithms/Julia/blob/main/CONTRIBUTING.md). Closes #138 
Recursive implementations could be added in the future.
> Added DFS and BFS: closes #138

- src/TheAlgorithms.jl
- src/math/eulers_totient.jl
- src/math/mersenne_prime.jl
- test/math.jl
Added mersenne prime checker and generator.
> Added Mersenne Primes

- src/TheAlgorithms.jl
- src/math/catalan_number.jl
- test/math.jl
In combinatorial mathematics, the Catalan numbers are a sequence of natural numbers that occur in various counting problems, often involving recursively defined objects.
Added function to generate the nth catalan number.
> Added Catalan Number function

- src/TheAlgorithms.jl
- src/math/divisors.jl
- test/math.jl
Added the following functions:
divisors: to find the divisors of a number
sum_divisors: to find the sum of the divisors of a number
aliquot_sum: to find the sum of the proper divisors of a number
> Added Divisor Functions

- docs/CODEOWNERS
Things added/changed:
- Add [codeowners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file.
> chore: add codeowners file

- src/TheAlgorithms.jl
- src/project-euler/problem_001.jl
- test/project-euler.jl
- test/runtests.jl
Added solution to Project Euler's Problem 1: Multiples of 3 or 5
https://projecteuler.net/problem=1
> Added Solution to Project Euler Problem 001

- src/TheAlgorithms.jl
- src/project-euler/problem_003.jl
- test/project-euler.jl
Added solution to project Euler's problem 3:  Largest prime factor
https://projecteuler.net/problem=3
> Added solution to Project Euler problem 003

- .github/workflows/format.yml
Things added/changed:
- Run formatter workflow on PRs.
> feat: run formatter workflow on PRs

- src/TheAlgorithms.jl
- src/project-euler/problem_004.jl
- src/sorts/bogo_sort.jl
- test/project-euler.jl
Added solution to project Euler's problem 4: Largest palindrome product
https://projecteuler.net/problem=4
> Added solution to Project Euler problem 004

- src/TheAlgorithms.jl
- src/project-euler/problem_005.jl
- test/project-euler.jl
Added solution to project Euler's problem 5: Smallest multiple
https://projecteuler.net/problem=5
> Added solution to Project Euler problem 005

- src/TheAlgorithms.jl
- src/project-euler/problem_006.jl
- test/project-euler.jl
Added solution to project Euler's problem 6: Sum Square Difference
https://projecteuler.net/problem=6
> Added solution to Project Euler problem 006

- src/TheAlgorithms.jl
- src/project-euler/problem_007.jl
- test/project-euler.jl
Added solution to project Euler's problem 7: 10001st prime
https://projecteuler.net/problem=7
> Added solution to Project Euler problem 007

- .gitpod.dockerfile
Things added/changed:
- Fix `.gitpod.dockerfile` issues.
> fix: `.gitpod.dockerfile` issues

- .github/workflows/format.yml
Things added/changed:
- Improve the Julia formatter workflow.
- One of the changes includes:
1. Able to run successfully on any PR or unprotected branch.
2. Commits and pushes automatically if there are any formatting changes to be done.
3. Shows the `diff` on the workflow logs.
> feat: improve the Julia formatter workflow

- src/project_euler/ProjectEuler.jl
- src/project_euler/problem_010.jl
- test/project_euler.jl
Added solution to project Euler's problem 10: Summation of primes
[projecteuler.net/problem=10](https://projecteuler.net/problem=10)
> Added solution to Project Euler problem 010

- src/project_euler/ProjectEuler.jl
- src/project_euler/problem_009.jl
- test/project_euler.jl
Added solution to project Euler's problem 9: Special Pythagorean triplet
[projecteuler.net/problem=9](https://projecteuler.net/problem=9)
> Added solution to Project Euler Problem 009

- docs/make.jl
- src/math/Math.jl
- src/math/divisors.jl
- test/math.jl
Added it as a part of math/divisors.jl
> Add function to find number of divisors

- src/cipher/Cipher.jl
- src/cipher/vigenere.jl
- test/cipher.jl
- Added vigenere.jl and tests to ciphers
> feat: Added Vigenère cipher

- src/math/Math.jl
- src/math/amicable_numbers.jl
- test/math.jl
Added a function to find all amicable pairs below n.
> Add Amicable Numbers

- src/project_euler/ProjectEuler.jl
- src/project_euler/problem_014.jl
- test/project_euler.jl
Added solution to Project Euler's problem 14: Longest Collatz Sequence
[projecteuler.net/problem=14](https://projecteuler.net/problem=14)
> Add solution to Project Euler Problem 014

- src/math/fibonacci.jl
- test/math.jl
This branch:
https://github.com/TheAlgorithms/Julia/blob/4da6bc6026f0824349a60a085bd9969d4f8cbaad/src/math/fibonacci.jl#L101
is not covered by existing tests and redundant. This PR fixes that.
> style: simplify `fib_iterative`

- test/searches.jl
The `linear_search` function is not really tested. This PR adds some meaningful tests for it. Similar to #193.
> tests: add tests for `linear_search`

- test/searches.jl
The `jump_search` function is not really tested. This PR adds some _meaningful_ tests for it.
> tests: add tests for `jump_search`

- test/matrix.jl
Added a test case _covering_ this line:
https://github.com/TheAlgorithms/Julia/blob/ede895a5e5e194cf09b184de08313c599463ad84/src/matrix/gauss_jordan_elim.jl#L38
> tests: add a test for `gauss_jordan` with row swap

- test/strings.jl
This PR adds a test case covering this line: https://github.com/TheAlgorithms/Julia/blob/ede895a5e5e194cf09b184de08313c599463ad84/src/strings/rabin_karp.jl#L58
> tests: add test for `rabin_karp`

- src/project_euler/ProjectEuler.jl
- src/project_euler/problem_010.jl
- src/project_euler/problem_015.jl
- test/project_euler.jl
Added solution to Project Euler's problem 15: Lattice Paths
[projecteuler.net/problem=15](https://projecteuler.net/problem=15)
> Add solution to Project Euler Problem 015

- src/basic/difference_arr.jl
- src/basic/prefix_sum.jl
- test/basic.jl
* Add docs to `prefix_sum`
* Specify the input array type in the docs for `DifferenceArray` (as any `Number` array)
* When making a copy, for clarity, use `copy(original)` instead of `Array(original)` in `DifferenceArray`
* Return an array of the correct `Number` type instead of an `Any` array, from `prefix_sum`
* Add more tests to `prefix_sum`
> Enhancements to "Basic": mainly docs 

- .gitpod.dockerfile
This PR updates `gitpod/workspace-base` to [`2023-10-19-14-24-02`](https://hub.docker.com/layers/gitpod/workspace-base/2023-10-19-14-24-02/images/sha256-7bc9afe251dc71cd50b7aaeebfd1ed80690a9080c43322e39a57fc9959f6af6d?context=explore).
> chore: update `gitpod/workspace-base` to `2023-10-19-14-24-02`

- test/data_structures.jl
This PR adds test covering this line:
https://github.com/TheAlgorithms/Julia/blob/8497c1ede63f05bf6ca0206d5db49fb3641ffa7d/src/data_structures/linked_list.jl#L142
Similar to #214.
> tests: add test for `LinkedList.get_node`

- src/math/Math.jl
- src/math/runge_kutta_integration.jl
- test/math.jl
Add a 4th order Runge-Kutta integration function, and some corresponding tests.
> feat: Add Runge-Kutta Integration
